const initialState = {
    categories: [
        {
            title: 'Countries',
            value: 'countries',
            words: [
                'SPAIN',
                'TURKEY',
                'NICARAGUA',
                'CROATIA',
                'MEXICO',
                'BELGIUM',
                'THAILAND',
                'AUSTRIA',
                'RUSSIA',
                'CANADA',
                'AFGHANISTAN',
                'ESTONIA',
                'INDONESIA',
                'LEBANON',
                'MADAGASCAR',
                'NETHERLANDS',
                'PORTUGAL',
                'SINGAPORE',
                'TAIWAN',
                'VENEZUELA',
                'YEMEN',
                'ZIMBABWE',
                'SWITZERLAND',
                'POLAND',
                'PARAGUAY',
                'JAMAICA',
                'GUATEMALA',
                'ETHIOPIA',
                'DENMARK',
                'CAMBODIA',
                'ARGENTINA',
                'BOLIVIA',
                'CAMBODIA',
                'EGYPT',
                'GUYANA'
            ]
        },
        {
            title: 'Beers & Breweries',
            value: 'beers',
            words: [
                'TRULY',
                'DRAKES',
                'COORS',
                'FOUNDERS',
                'STONE',
                'DESCHUTES',
                'GUINNESS',
                'CORONA',
                'HEINEKEN',
                'NEWCASTLE',
                'BUDWEISER',
                'BUSCH',
                'MODELO',
                'ABITA',
                'ALASKAN',
                'ALLAGASH',
                'BRIDGEPORT',
                'FIRESTONE',
                'KALAMAZOO',
                'LAGUNITAS',
                'LEINENKUGEL',
                'MILLER',
                'OMMEGANG',
                'PYRAMID',
                'REDHOOK',
                'ROGUE',
                'SUMMIT',
                'VICTORY',
                'YUENGLING',
                'DRAGOON',
                'CORIOLIS',
                'TROPICALIA',
                'PIPEWORKS',
                'REVOLUTION',
                'ELYSIAN'
            ]
        },
        {
            title: 'Board Games',
            value: 'boardGames',
            words: [
                'MONOPOLY',
                'BATTLESHIP',
                'CHESS',
                'PANDEMIC',
                'RISK',
                'LIFE',
                'SCRABBLE',
                'DOMINION',
                'PICTIONARY',
                'BACKGAMMON',
                'YAHTZEE',
                'AGRICOLA',
                'CHECKERS',
                'CANDYLAND',
                'TROUBLE',
                'OPERATION',
                'CRANIUM',
                'SCATTERGORIES',
                'MAHJONG',
                'TABOO',
                'MANCALA',
                'BALDERDASH',
                'ACQUIRE',
                'STRATEGO',
                'BLOKUS',
                'CIVILIZATION',
                'DIPLOMACY',
                'RESISTANCE',
                'SHOGUN',
                'PARCHEESI',
                'BANANAGRAMS',
                'ZOMBIES',
                'CODENAMES',
                'SCYTHE',
                'TELESTRATIONS'
            ]
        },
        {
            title: 'Movies',
            value: 'movies',
            words: [
                'INCREDIBLES',
                'HALLOWEEN',
                'TITANIC',
                'SCREAM',
                'VENOM',
                'SEARCHING',
                'TERMINATOR',
                'OVERLORD',
                'DELIVERANCE',
                'PSYCHO',
                'AIRPLANE',
                'MEMENTO',
                'BRAVEHEART',
                'INCEPTION',
                'AMADEUS',
                'GHOSTBUSTERS',
                'GLADIATOR',
                'AMELIE',
                'GOODFELLAS',
                'CASABLANCA',
                'SCARFACE',
                'UNFORGIVEN',
                'SPLIT',
                'TRAINSPOTTING',
                'CADDYSHACK',
                'BEETLEJUICE',
                'GOLDFINGER',
                'PHILADELPHIA',
                'SPACEBALLS',
                'JUMANJI',
                'UNBREAKABLE',
                'ARMAGEDDON',
                'POLTERGEIST',
                'FANTASIA',
                'PINOCCHIO'
            ]
        },
        {
            title: 'Animals',
            value: 'animals',
            words: [
                'JELLYFISH',
                'KOALA',
                'HIPPOPOTAMUS',
                'HYENA',
                'ZEBRA',
                'HEDGEHOG',
                'CAMEL',
                'FLAMINGO',
                'IGUANA',
                'LEMUR',
                'AARDVARK',
                'BANDICOOT',
                'CAIMAN',
                'CATERPILLAR',
                'CHICKEN',
                'ALBATROSS',
                'BEAVER',
                'CROCODILE',
                'DALMATIAN',
                'GIRAFFE',
                'KANGAROO',
                'JAGUAR',
                'LEMMING',
                'OPOSSUM',
                'PENGUIN',
                'RHINOCEROS',
                'SCORPION',
                'TORTOISE',
                'SQUIRREL',
                'WOLVERINE',
                'BARRACUDA',
                'CHAMELEON',
                'DINGO',
                'GERBIL',
                'HUMMINGBIRD'
            ]
        }
    ],
    chosenWord: [],
    remainingLives: 7,
    validGuesses: [],
    clickedCategory: ''
};

const categoryReducer = (state = initialState, action) => {
    switch(action.type) {
        case 'SELECT_CATEGORY':
            return {
                chosenWord: Array.from(
                    state.categories.find(category => category.value === action.value).words[action.i]
                ),
                remainingLives: 7,
                categories: state.categories,
                clickedCategory: action.value
            }
        case 'NEW_GAME':
            return initialState
        default:
            return state
    }
};

export default categoryReducer;
